### ISSUE TITLE
QT import error: PySide6 - Shiboken.replaceModuleDict

### ISSUE THREAD

**Issue by sebimoe** [BBC-Esq/ctranslate2-faster-whisper-transcriber#11]
Installed using `python .\setup.py` in a new venv using Python 3.11.9.
```
--- Installation Summary ---

All libraries installed successfully on the first attempt.
Installation was successful! The program is ready to use.
To run it, enter the command: python ct2_main.py

Total installation time: 00:03:19.20
```

Running the app gives me:
```
(ctranslate2-faster-whisper-transcriber-3.3.0) PS C:\programs\ctranslate2-faster-whisper-transcriber-3.3.0> python ct2_main.py
Traceback (most recent call last):
  File "C:\programs\ctranslate2-faster-whisper-transcriber-3.3.0\ct2_main.py", line 23, in <module>
    from PySide6.QtWidgets import QApplication
  File "C:\programs\ctranslate2-faster-whisper-transcriber-3.3.0\Lib\site-packages\PySide6\__init__.py", line 141, in <module>
    Shiboken.replaceModuleDict(sys.modules["PySide6"], SubModule, ModuleDict(globals()))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'shiboken6.Shiboken' has no attribute 'replaceModuleDict'
```

Any ideas what could be wrong?

**Comment by auadbigname** [comment]
Just get a new version of the shiboken6

pip install --upgrade shiboken6

**Comment by BBC-Esq** [comment]
hey, sorry for the delay and thanks for pointing this out.  Actually, "shiboken" will automatically be installed when ```setup.py``` installs pyside6.  I accidentally added it to the "libraries" list of things to install in addition when that's unnecessary and creates the version conflict...Simply remove the shiboken line and reinstall and it should work fine.

**Comment by BBC-Esq** [comment]
Resolved.
